import {
  ClerkProvider,
  SignedIn,
  UserButton
} from "@clerk/nextjs";

function Header() {
  return (
    <header
      style={{ display: "flex",paddingTop:50, justifyContent: "center"}}
    >
      <SignedIn>
        {/* Mount the UserButton component */}
        <UserButton />
      </SignedIn>
    </header>
  );
}
/*
const getHeader =()=>{
  if ([`/sign-in`,`/sign-out`].includes(router.pathname))
return ;

return (<Header/>)}*/

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (<ClerkProvider>
    <html lang="en">
      <Header/>
        <body className={inter.className}>
{children}</body>  
    </html></ClerkProvider>
  );
}

